# Split World Config

# Global game mode to default to for worlds with split world disabled, you can override this per-world in their config
default_game_mode: "survival"

# Disables the welcome message for everyone when set to true, default is false. Players can always individually disable
# the welcome message with the /understood command
disable_welcome_message: false

# when set to true, this will change the XP loss behavior on death to lose a specified percentage of XP upon death
enable_xp_mod: false
xp_loss_percentage: 25.0

# allows players to use the specified commands on the creative side. Make sure that by
# default these players have permission to use them. split-world will make sure they
# can't use fill, setblock, or clone on or targeting blocks outside of creative zones
manage_creative_commands: true
creative_commands:
  - fill
  - setblock
  - clone

# set a custom respawn point, allows you to spawn underground but not in solid blocks.
custom_respawn: false
respawn_world: "world"
respawn_location:
  x: 140.0
  y: 53.0
  z: -64.0
  yaw: 0.0
  pitch: 0.0

# custom spawn protection
competition_area:
  - x1: 0
  - y1: 0
  - z1: 0
  - x2: 0
  - y2: 0
  - z2: 0

# Per world configs, this should theoretically work for any world but is only tested on default minecraft worlds
world_configs:
  - world_name: "world"

    # OPTIONAL
    # override the global default game mode, this applies whether split world is enabled for the world or not
    default_game_mode: "survival"

    # REQUIRED
    # when true, split-world will manage the game mode of all players and keep their inventories separate by saving
    # and loading them when they cross the border
    enabled: true

    # REQUIRED when enabled: true
    # which axis should the border be placed on
    border_axis: "X"

    # REQUIRED when enabled: true
    # changing this will place the border at the specified coordinate, being on the "negative" side is defined by
    # having a coordinate value less than border_location value + half of the border_width.
    border_location: 0

    # REQUIRED when enabled: true
    # positive or negative, the positive side is any value of the [border_axis] greater than the [border_location],
    # the negative side is any value of the [border_axis] less than [border-location]
    creative_side: "negative"

    # REQUIRED when enabled: true
    # defines the width of the border, while in this zone players will be put in adventure mode, hunger will not deplete
    # this is how many blocks on each side of the border will be considered buffer zones.
    # The total size of the border is border_width * 2
    border_width: 5

    # REQUIRED when enabled: true
    # Replace all blocks with bedrock along the border as players encounter it.
    replace_border_blocks: true

    # REQUIRED when enabled: true
    # Prevent monsters from spawning on the creative side
    no_creative_monsters: true

  - world_name: "world_nether"
    default_game_mode: "survival"
    enabled: false
    border_axis: "X"
    border_location: 0
    creative_side: "negative"
    border_width: 10
    replace_border_blocks: true
    no_creative_monsters: true

  - world_name: "world_the_end"
    default_game_mode: "survival"
    enabled: false

enable_easter_eggs: false