###
#  Split World Config
#  Please report bugs and exploits:
#     https://github.com/snaco/split-world-plugin/issues/
#  A copy of the latest default config can be found at:
#     https://github.com/snaco/split-world-plugin/blob/master/src/main/resources/config.yml
#  When updating, please make sure to read the changelog:
#     https://github.com/snaco/split-world-plugin/releases
###

# Global game mode for all worlds that are disabled
# or not configured with a default_game_mode
default_game_mode: "survival"

# Disables the welcome message for everyone when set
# to true. Players can always individually disable
# the welcome message with the /understood command
disable_welcome_message: false

# When set to true, this will change the XP loss
# behavior on death to lose the specified percentage
enable_xp_mod: false
xp_loss_percentage: 25.0

# Allow players to use the specified commands
# on the creative side. Players must have permission
# to use the listed command. split-world will ensure
# that any commands listed will only be executable
# on the creative side. Additionally, it will always
# ensure that the fill, setblock, and clone commands
# cannot include blocks outside the creative zone.
#
# Be careful choosing which commands you allow on the
# creative side. If the command takes coordinates as
# arguments, they can be used to affect things outside
# the creative zone.
manage_creative_commands: true
creative_commands:
  - fill
  - setblock
  - clone

# Set a custom respawn point. Will spawn player at the
# nearest safe Y coordinate above the specified location
# where safe is defined by not suffocating or falling.
custom_respawn: false
respawn_world: "split_world"
respawn_location:
  x: 140.0
  y: 53.0
  z: -64.0
  yaw: 0.0
  pitch: 0.0


# secret easter-eggs
enable_easter_eggs: false

# Per world configs
world_configs:
  - world_name: "split_world"
    enabled: true
  - world_name: "creative_world"
    game_mode: "creative"

  # These are the default values for enabled worlds:
  #
  # border_position: "X"
  # border_location: 0
  # creative_side: "negative"
  # border_width: 5
  # replace_border_blocks: true
  # no_creative_monsters: true
  #
  # you can also set the default_game_mode for a world
  # to override the global default_game_mode for just that
  # world without needing to enable split-world
  #
  # default_game_mode: "survival"
  #
  # example world config to enable split-world for the world
  #  - world_name: "world"
  #    enabled: true
  #
  # example world config to make a creative world
  #  - world_name: "creative_world"
  #    default_game_mode: "creative"
  #
  # example world config with custom border settings
  #
  #  - world_name: "world"
  #    enabled: true
  #    default_game_mode: "adventure"
  #    border_position: "Z"
  #    border_location: 200
  #    creative_side: "positive"
  #    border_width: 2
  #    replace_border_blocks: true
  #    no_creative_monsters: false
  #
