name: SplitWorld
version: 3.1.1+1.19
main: tech.snaco.split_world.SplitWorld
description: Splits the world into two game modes
author: snaco
website: https://papermc.io
api-version: 1.19
commands:
  understood:
    description: You understand the nature of the split world and don't want to see the welcome message anymore.
    usage: /understood
    permission: split-world.understood
  disable-split-world:
    description: disables split world game mode switching
    usage: /disable-split-world
    permission: split-world.disable-split-world
  enable-split-world:
    description: enables split world game mode switching
    usage: /enable-split-world
    permission: split-world.enable-split-world
  open-survival:
    description: opens the world to survival
    usage: /open-survival
    permission: split-world.open-survival
  set-spawn-builder:
    description: sets if the player can continue building in spawn after the competition ends.
    usage: /set-spawn-builder <player> <true|false>
    permission: split-world.set-spawn-builder
  play-border-sound:
    description: plays a sound when you cross a split world border
    usage: /play-border-sound <true|false>
    permission: split-world.play-border-sound
